Machines:
  machine1:
    reels:
      '1':
      - 331-50
      - 266-50
      - 264-50
      '2':
      - 331-50
      - 266-50
      - 264-50
      '3':
      - 331-50
      - 266-50
      - 264-50
      '4':
      - 331-50
      - 266-50
      - 264-50
    rewards:
    - 264,264,264,264:5
    - 331,266,266,331:3
    - 266,264,264,266:4
    - 331,266,264,331:6
    - 331,331,331,331:2
    - 266,266,266,266:10
    economy:
      use_economy: true
      cost: 10
    bet_limits:
      enabled: false
      allowed:
      - 266-1
      - 264-1
    messaging:
      message: '$6$[MCCasino] $7$$name$ won $$amount$!'
      send_to: players_nearby
      exclude_winner: true
      radius: 20
  machine2:
    reels:
      '1':
      - 4-50
      - 5-50
      - 1-50
      '2':
      - 4-50
      - 5-50
      - 1-50
      '3':
      - 4-50
      - 5-50
      - 1-50
      '4':
      - 4-50
      - 5-50
      - 1-50
      '5':
      - 4-50
      - 5-50
      - 1-50
    rewards:
    - 1,1,1,1,1:5
    - 4,5,1,5,4:3
    - 5,1,4,1,5:4
    - 4,5,1,5,4:6
    - 4,4,4,4,4:2
    - 5,5,5,5,5:10
    - 5,5,5,5,5:10
    - X,X,5,X,X:10
    economy:
      use_economy: false
      cost: 10
    bet_limits:
      enabled: true
      allowed:
      - 266-1
      - 264-1
    messaging:
      message: '$6$[MCCasino] $7$$name$ won $amount$ $item$(s)!'
      send_to: world
      exclude_winner: true
      radius: 15
      
    #Black: $0$
    #Dark blue: $1$
    #Dark green: $2$
    #Dark aqua: $3$
    #Dark red: $4$
    #Dark purple: $5$
    #Gold: $6$
    #Gray: $7$
    #Dark gray: $8$
    #Blue: $9$
    #Green: $a$
    #Aqua: $b$
    #Red: $c$
    #Light purple: $d$
    #Yellow: $e$
    #White: $f$
    #$name$ = player's name
    #$amount$ = amount of items/money won
    #$item$ = name of item won
